main:
  params: [ workflowConfig ]
  steps:
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - location_id: "global"
    - loadTeamStatsRawToBq:
        call: googleapis.bigquery.v2.jobs.insert
        args:
          projectId: ${project_id}
          body:
            configuration:
              load:
                destinationTable:
                  datasetId: ${workflowConfig.dataset}
                  projectId: ${project_id}
                  tableId: ${workflowConfig.team_stat_raw_table}
                referenceFileSchemaUri: ${workflowConfig.team_stats_raw_bq_schema_uri}
                sourceFormat: ${workflowConfig.team_stats_raw_bq_source_format}
                sourceUris: ${workflowConfig.team_stats_raw_files_hot_source_uri}
                createDisposition: ${workflowConfig.team_stats_raw_bq_create_disposition}
                writeDisposition: ${workflowConfig.team_stats_raw_bq_write_disposition}
        result: loadTeamStatsRawToBqResult
    - runQueryTransformToTeamStatsDomainAndLoadToBQ:
        call: googleapis.bigquery.v2.jobs.query
        args:
          projectId: ${project_id}
          body:
            useLegacySql: false
            query: "{{sql_query}}"
        result: queryResult
    - copyProcessedFilesToColdBucket:
        call: googleapis.cloudbuild.v1.projects.builds.create
        args:
          projectId: ${project_id}
          parent: ${"projects/" + project_id + "/locations/" + location_id}
          body:
            serviceAccount: ${sys.get_env("GOOGLE_CLOUD_SERVICE_ACCOUNT_NAME")}
            options:
              logging: CLOUD_LOGGING_ONLY
            steps:
              - name: gcr.io/google.com/cloudsdktool/cloud-sdk:455.0.0-slim
                script: ${"gsutil cp " + workflowConfig.team_stats_raw_files_hot_source_uri + " " + workflowConfig.team_stats_raw_files_cold_destination_uri}
        result: resultCloudBuildCopy
    - returnResult:
        return: ${resultCloudBuildCopy}